version : 2
updates :
  - package-ecosystem : "npm" # "pip" , "maven", "gradle", "nuget", "composer"
  directory : "/"
  schedule :
    interval : "weekly" # "daily", "monthly" , "yearly"
  commit-message:
    prefix : "chore(deps)"