import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MSWComponent } from "./_components/MSWComponents";
import AuthSession from "./_components/AuthSession";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/** Layout
 * 1. 로그인 했을때와 로그아웃 했을때의 차이
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MSWComponent />
        {/* useSesstion 을 확인하기 위한 Provider */}
        <AuthSession>
          <div>{children}</div>
        </AuthSession>
      </body>
    </html>
  );
}
